version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}